### ISSUE TITLE
unable to see list of cookies

### ISSUE THREAD

**Issue by jsrees** [vanowm/FirefoxCookiesManagerPlus#45]
Windows 7 Firefox 35.0.1
When I open Cookies Manager, I see an empty field. and the top bar shows 
"Cookies Manager 1.5.2. [showing 0 of 3090, 0 selected]"
How do I get to see and edit the 3090 cookies on my computer?
with thanks in advance

**Comment by vanowm** [comment]
Just hit the refresh button next to filter field.

This issue has been fixed in upcoming v1.6

**Comment by jsrees** [comment]
this doesn't work for me! The field still stays blank.

**Comment by jsrees** [comment]
this doesn’t work for me. The field still stays blank.

**Comment by vanowm** [comment]
What does the error console say? (CTRL + SHIFT + J)
I've seen this issue on my main browser before (the checkboxes also look funky, skinny and can't be checked, but the refresh button worked), and it went away by itself.

Try uncheck everything in view menu, including tree submenu and restart the browser.

At the moment I can only offer to wait for the new version, which is not ready yet, due to some serious performance issue.

**Comment by jsrees** [comment]
CTRL+SHIFT +J – no error console or other box appears
have unchecked everything as you suggested, have removed and re-downloaded and re-installed Cookies Manager, but issue remains unchanged.
The check boxes are not looking strange, it’s possible to check and uncheck them as normal.
